[package]
name = "mirage_tank"
version = "0.1.0"
authors = ["Aloxaf <bailong104@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.19.0"

[dependencies.clap]
version = "2.32.0"
features = ["yaml"]

[profile.release]
lto = true
opt-level = 3
